### ISSUE TITLE
Add Population, Surface Area and other Stats  for Jersey, Martinique, Mayotte, Reunion, Taiwan and Western Sahara

### ISSUE THREAD

**Issue by aditigarg08** [foss42/foss42-core#111]
Hello @ashitaprasad 
I found out that the Population, Surface Area and other Stats for Jersey, Martinique, Mayotte, Reunion, Taiwan and Western Sahara was missing. I would like to add that data to this repository. 

Please assign this issue under GSSOC'24 and add the labels, so that I can go ahead with this task.
Thanks

**Comment by ashitaprasad** [comment]
What is the source. Share link

**Comment by aditigarg08** [comment]
**Source**-

**Jersey** - https://datareportal.com/reports/digital-2024-jersey?rq=jersey
**Martinique**- https://datareportal.com/reports/digital-2024-martinique?rq=Martinique
**Mayotte** - https://datareportal.com/reports/digital-2024-mayotte?rq=Mayotte
**Reunion** - https://datareportal.com/reports/digital-2024-reunion?rq=Reunion
**Taiwan** - https://datareportal.com/reports/digital-2024-taiwan?rq=Taiwan
**Western Sahara** - https://datareportal.com/reports/digital-2024-western-sahara?rq=Western%20Sahara

**Comment by aditigarg08** [comment]
Hello @ashitaprasad
Can you please tell that why my contributions are paused and then it is marked as completed and then closed without assigning it to me.
I really wanted to work on this project. Kindly assign this issue to me.

Thank you
