### ISSUE TITLE
Improve/Update Readme Section

### ISSUE THREAD

**Issue by PilotAxis** [foss42/foss42-core#25]
Hi @animator, I am a GSSoC'24 contributor. I would like to contribute in your project. I can improve the Readme Section of your Repository. I can add many details to the Readme Section which will look interesting and easy to understand what the project says and how the project can be run locally. Please let me know if I am assigned to do this...

**Comment by Vaishali-ajmera** [comment]
Hello! As a contributor in GSSoC 2024, I'm excited to make my first-ever contribution. I'd love the opportunity to enhance your project's Readme Section, making it more user-friendly and engaging. Please assign this task to me.

**Comment by itssahillwhat** [comment]
Hello, I am a GSSOC 2024 Contributor.
I would like to fix the issue in your project
can you please assign the task to me?
and also can you please label the issue?(like gssoc, level 1\2\3) .so that when we pull the request it will show in the leaderboard

**Comment by MrCodYrohit** [comment]
👋 Hello there! As a contributor to GSSoC 2024, I'm eager to embark into the open-source contributions. I'm keen to revamp your project's Readme Section, infusing it with user-friendliness and engagement. Would you kindly assign me this task? Also, could you specify the appropriate level for labeling purposes? Much appreciated! 🚀

**Comment by PilotAxis** [comment]
Hey, @MrCodYrohit @itssahillwhat and @Vaishali-ajmera , I am also a contributor and created this issue. You can create your another issue or whatever you feels like to do in the project, I cannot assign you for any role to do in the project, create your issue or comment on the Project's Admin issues to do contribution! Hope you all understands...

**Comment by ashitaprasad** [comment]
@PilotAxis @Vaishali-ajmera @itssahillwhat @MrCodYrohit 
The README and Contributing Guide has been updated to better guide you in making your contribution to the project.
