### ISSUE TITLE
Add of CODE_OF_CONDUCT.md file

### ISSUE THREAD

**Issue by Pranjalll01** [foss42/foss42-core#27]
HEY
Pranjal Kushwaha here , Contributor@GSSoc'24
repo currently lacks a CODE_OF_CONDUCT.md file, which is an important resource for guiding potential contributors on how to engage with the project effectively. A CODE_OF_CONDUCT.md file outlines the contribution guidelines, coding standards, and procedures for submitting pull requests, thus streamlining the contribution process and ensuring consistency across contributions.

could you please assign this to me ?

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by akshatsharma2407** [comment]
Hello, I am fully capable of writing the CODE_OF_CONDUCT section as a GSSoC contributor. Kindly assign me this issue as I possess intermediate knowledge of the technology utilized in your project. I am confident that I am the best fit for this task.

**Comment by ashitaprasad** [comment]
It is now available.
