### ISSUE TITLE
Learn.md

### ISSUE THREAD

**Issue by sanjay-kv** [foss42/foss42-core#32]
Learn repos should have a LEARN.md file to teach student how to build your project step by step. You can explain how to build your project with text, code snippets, images, or even short (5 minute) long video lessons. As the maintainer of a Learn repo, the LEARN.md file requires you to think critically about how to explain the building of your project and how to also make it engaging. We don't expect you to be an expert teacher, but we would like you to reflect on how difficult it was to get to your level of knowledge, and then provide friendly guidance to help other students to learn.

Reference: https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/Learn.md

**Comment by SAISUPRIYAPAVARALA** [comment]
I am a GSSoc'24 contributor. I want to work on this task. Could you please assign me this task? I have already analyzed your project , along with the other 2 repositories related to this project.

**Comment by himanshiduseja** [comment]
Greetings Sir, @sanjay-kv , I have studied the project and  I can say am capable of writing Learn.md for this project since have worked on projects related to this tech stack. As a GSSoC contributor, i would like to work on the same. It would be great if you could assign me this issue.
