### ISSUE TITLE
Improvement: Add, remove leading zero function in text/humanize.py

### ISSUE THREAD

**Issue by princekhunt** [foss42/foss42-core#45]
Hello,

There is a function already a function for removing trailing zeros, named [**remove_trailing_zeros**](https://github.com/foss42/foss42-core/blob/40ce5a51162f805ab9e6f76c1271e669103ba6d8/foss42/text/humanize.py#L8).

I want propose a function that **removes the leading zero** in given number.
example:
**request:0000123**
**response:123**

Kindly Assign this to me, if you believe this functionality would be helpful.

Thanks

**Comment by animator** [comment]
This repo is only for function development.
API Development is in another repo.
