### ISSUE TITLE
Addition of female population percentage of Vanuatu,Venezuela,Vietnam.

### ISSUE THREAD

**Issue by 1911aditi** [foss42/foss42-core#50]
Hi, I want to add the female population percentage for Vanuatu,Venezuela,Vietnam.
Can I go ahead?
also i want to contribute in GSSoC'24

**Comment by B-Mittal** [comment]
Hello,
I am here to learn and want to go ahead with the issue of Addition of female population percentage of Vanuatu,Venezuela,Vietnam.
Kindly alow me to do so.
