### ISSUE TITLE
Addition of female population percentage of syria and Srilanka

### ISSUE THREAD

**Issue by 1911aditi** [foss42/foss42-core#56]
Hi, I want to add the female population percentage for syria and Srilanka.
Can I go ahead?

**Comment by ArismitaM** [comment]
Can you please assign this task to me

**Comment by GANGSTER0910** [comment]
Can you assign me this task if possible

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in ML. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
@ashitaprasad  Sir, I would really like to work on this issue, so please assign it to me.

**Comment by B-Mittal** [comment]
Hello,
I am here to learn and thus move forward with the issue of Addition of female population percentage of syria and Srilanka .
Kindly allow me to do so.
