### ISSUE TITLE
Modifying update.py

### ISSUE THREAD

**Issue by PrajwalaY26** [foss42/foss42-core#57]
update.py is now working fine, but it can be improved with some small changes.

**Comment by PrajwalaY26** [comment]
I am a gssoc'24 contributor and I think I have the potential to work on this issue. I would like to add 'with' statement for handling the README file to improve the code. Kindly assign me this issue, so I can work on it.

**Comment by merciajeno** [comment]
Hey Project Admin. I am an intermediate python programmer. Can you assign me the task?

**Comment by animator** [comment]
There is no such file.
