### ISSUE TITLE
Addition of Sub-division data of Spain.

### ISSUE THREAD

**Issue by Arghya-Banerjee** [foss42/foss42-core#61]
I want to add the subdivision data for Spain. Can I go ahead with this issue please?
Thank you.

**Comment by yashpawar6849** [comment]
I am interested to work on this project assign me the task please.

**Comment by B-Mittal** [comment]
Hello,
I really want to go ahead and learn with the issue of Addition of Sub-division data of Spain.
Kindly allow me to do so
