### ISSUE TITLE
Addition of Sub-division data of Switzerland

### ISSUE THREAD

**Issue by Antiquely3059** [foss42/foss42-core#62]
Hi, I want to add the Sub-division data of Switzerland.
Can I go ahead ?

**Comment by manyahegde** [comment]
I would like to contribute. Please assign me the task.

**Comment by cpratik1307** [comment]
I am thrilled to be participating in GirlScript Summer of Code 2k24 as a passionate computer science student with a keen interest in web development. I am eager to contribute to your project and leverage my skills to make meaningful contributions. I look forward to collaborating with you and the team to create impactful solutions.
 Sir, I would really like to work on this issue, so please assign it to me.

**Comment by B-Mittal** [comment]
Hello,
I want to move forward with the Addition of Sub-division data of Switzerland.
Looking forward to learn and contribute.

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can take this up under GSSoC'24. Lemme know. :)
