### ISSUE TITLE
Addition of Sub-division data of Brazil

### ISSUE THREAD

**Issue by Antiquely3059** [foss42/foss42-core#72]
Hi, I want to add the Sub-division data of Brazil.
Can I go ahead ?

**Comment by Alladi-Varsha** [comment]
Hi, I want to add the Sub-division data of Brazil?
Can I go ahead?
also I want to contribute in GSSoC'24

**Comment by masterboy376** [comment]
Hello @ashitaprasad , I would like to work on the issue under GSSoC'24.

**Comment by why-Radhika** [comment]
Hi I have added the subdivision data for Brazil. Pleas assign this issue to me. I want to create PR.
