### ISSUE TITLE
addition of female population percentage of jordan and jamaica.

### ISSUE THREAD

**Issue by 1911aditi** [foss42/foss42-core#74]
Hi, I want to add the female population percentage for jordan and jamaica.
Can I go ahead?

**Comment by B-Mittal** [comment]
Hi, I want to go ahead with the issue of addition of female population percentage of jordan and jamaica. 
Kindly allow me to do so

**Comment by Uditrana2** [comment]
hii i want also want to explore this issue of addition . kindly allow me to do so
