### ISSUE TITLE
addition of female population percentage of cuba and cyprus.

### ISSUE THREAD

**Issue by 1911aditi** [foss42/foss42-core#75]
Hi, I want to add the female population percentage for cuba and cyprus.
Can I go ahead?

**Comment by 22wh1a05a8** [comment]
Hey! I would like to add the female population percentage of Cuba and Cyprus. Can I proceed with it?

**Comment by masterboy376** [comment]
Hello @ashitaprasad , I would like to work on the issue under GSSoC'24.
