### ISSUE TITLE
Addition of Sub-division data of France.

### ISSUE THREAD

**Issue by Arghya-Banerjee** [foss42/foss42-core#78]
I want to add the subdivision data for France. Can I go ahead with this issue please?
Thank you.

**Comment by masterboy376** [comment]
Hello @ashitaprasad , I would like to work on the issue under GSSoC'24. I am now available.

**Comment by why-Radhika** [comment]
Hi I have added the sub division data of France. Please assign this issue to me. I want to create a PR

**Comment by ananyabansal16** [comment]
If this issue is still pending, I can take this up under GSSoC'24. Lemme know. :)

**Comment by mrmahi2003** [comment]
if its possible I can work on it if its fine for you let me know
