### ISSUE TITLE
Logo Design For foss42.geo 

### ISSUE THREAD

**Issue by MehtabAsHellic** [foss42/foss42-core#79]
I will design the **old school tech kind-off logo** for foss42 because **it so clean UI** you have I really like it. 
Will add the logo at the top-right, mention below :
![needlogo](https://github.com/foss42/foss42-core/assets/101495398/2c2f6041-1a56-405d-ac4e-996dcff53bef)

**[https://sites.google.com/view/uibymehtab](https://github.com/Nactore-Org/Nacto-Care/issues/url)

let me know by check out my portfolio**

**Comment by masterboy376** [comment]
Hello @ashitaprasad , I would like to work on the issue under GSSoC'24. I am now available.

**Comment by ashitaprasad** [comment]
Please read the contributing guide to understand what is required.
