### ISSUE TITLE
Add a function to get detailed country information

### ISSUE THREAD

**Issue by SamFusedBits** [foss42/foss42-core#82]
In the country.py file, we need to add a function that takes an ISO Alpha-2 or Alpha-3 country code and returns a dictionary with all the details about the country (name, area, population, etc.)

**Comment by ashitaprasad** [comment]
This is currently not required.

**Comment by SamFusedBits** [comment]
Thank you for your feedback. I'll remove it for now and we can revisit it if needed later.
